[boris]
  version = 1

[build.dist-7-10-build]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-build"]
    ]

[build.dist-7-10-cli]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-cli"]
    ]

[build.dist-7-10-process]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-process"]
    ]

[build.dist-7-10-sass]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-sass"]
    ]

[build.branches-7-10-build]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-build"]
    ]

[build.branches-7-10-cli]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-cli"]
    ]

[build.branches-7-10-process]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-process"]
    ]

[build.branches-7-10-sass]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-sass"]
    ]

[build.dist-validate]
  command = [["validate-respect"]]

[build.all-rebased]
  command = [["rebased"]]

[build.all-submodules]
  command = [["dangling-refs"]]
