[boris]
  version = 1

[build.dist-7-10]
  command = [
      ["bin/master", "build", "dist-7-10", "-C", "loom-cli"]
    ]

[build.branches-7-10]
  command = [
      ["bin/master", "build", "branches-7-10", "-C", "loom-cli"]
    ]

[build.rebased]
  command = [["rebased"]]

[build.validate]
  command = [["validate-respect"]]
