[master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20170613033625-fddfe03/master-haskell-20170613033625-fddfe03"
  version = 1
  sha1 = "0a9e91a8c3373a402c5f2c4fc8d9aabb210c03b3"

[build.dist]
  GHC_VERSION="7.10.2"
  CABAL_VERSION = "1.24.0.0"
  PURESCRIPT_VERSION = "0.8.5.0"

[build.dist-7-10]
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_MASTER"
  PUBLISH_EXECUTABLES = "loom"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"
  CACHE = "true"

[build.dist-8-0]
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_MASTER"
  PUBLISH_EXECUTABLES = "loom"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"

[build.branches-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"
  CACHE = "true"

[build.branches-8-0]
  GHC_VERSION = "8.0.1"
  CABAL_VERSION = "1.24.0.0"
