[master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20170612225732-bc65184/master-haskell-20170612225732-bc65184"
  version = 1
  sha1 = "33ccece9916394065d60afd4240b07007390d712"

[build.dist]
  GHC_VERSION="7.10.2"
  CABAL_VERSION = "1.24.0.0"
  PURESCRIPT_VERSION = "0.8.5.0"

[build.dist-7-10]
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_MASTER"
  PUBLISH_EXECUTABLES = "loom"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"
  PURESCRIPT_VERSION = "0.8.5.0"
  CACHE = "true"

[build.branches-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"
  PURESCRIPT_VERSION = "0.8.5.0"
  CACHE = "true"
