[master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20160614225955-a2cc8b9/master-haskell-20160614225955-a2cc8b9"
  version = 1
  sha1 = "f827e1ff43bcaa325d128662391d95a8b4d65525"

[build.dist]
  GHC_VERSION="7.10.2"
  CABAL_VERSION = "1.22.4.0"
  PURESCRIPT_VERSION = "0.8.5.0"

[build.dist-7-10]
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_MASTER"
  PUBLISH_EXECUTABLES = "loom"
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_MASTER"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"
  PURESCRIPT_VERSION = "0.8.5.0"

[build.branches-7-10]
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_BRANCHES"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"
  PURESCRIPT_VERSION = "0.8.5.0"
